// This file defines the common data structures used throughout the application.

/**
 * Represents a major tourist destination.
 */
export interface Destination {
  name: string;
  description: string;
  image: string;
  lat: number;
  lon: number;
}

/**
 * Represents an item related to tribal culture (art, festivals, etc.).
 */
export interface TribalItem {
  name: string;
  description: string;
  image: string;
}

/**
 * Parameters for generating a travel itinerary with the Gemini API.
 */
export interface ItineraryParams {
  days: number;
  interests: string[];
  budget: string;
}

/**
 * Represents a community-submitted "hidden gem" location.
 * The `_id` is generated by the database and is optional on creation.
 */
export interface HiddenGem {
  _id?: string;
  name: string;
  description: string;
  location: string;
  submittedBy: string;
  imageUrl?: string;
  userTags?: string[]; // The tags the user enters
  aiTags?: string[]; // Tags generated by the AI
  aiInsight?: string; // A helpful tip generated by the AI
}

/**
 * Represents the possible weather conditions.
 */
export type WeatherCondition = 'Sunny' | 'Cloudy' | 'Rainy' | 'Stormy';

/**
 * Represents the weather information for a specific city.
 */
export interface WeatherInfo {
  city: string;
  temperature: number;
  condition: WeatherCondition;
  description: string;
}

/**
 * Represents a single message in the chatbot conversation.
 */
export interface ChatMessage {
  sender: 'user' | 'bot';
  text: string;
}
